service: originate-notify-job

plugins:
  - serverless-bundle

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  tracing:
    lambda: true

  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: '*'

functions:
  notify:
    handler: notify.main
    events:
      - sns:
        'Fn::ImportValue': ProjectPurchasedTopicArn-${self:custom.stage}

