service: originate-billing-api

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  tracing:
    lambda: true

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
    ProjectPurchasedTopicArn:
      Ref: ProjectPurchasedTopic

  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join:
          - ''
          -
            - 'arn:aws:ssm:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':parameter/stripeSecretKey/*'

    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - Ref: ProjectPurchasedTopic

functions:
  # Defines an HTTP API endpoint that calls the main function in billing.js
  # - path: url path is /billing
  # - method: POST request
  billing:
    handler: billing.main
    events:
      - http:
          path: projects/billing
          method: post
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    ProjectPurchasedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: project-purchased-${self:custom.stage}

  Outputs:
    ProjectPurchasedTopicArn:
      Value:
        Ref: ProjectPurchasedTopic
      Export:
        Name: ProjectPurchasedTopicArn-${self:custom.stage}